CREATE TABLE IF NOT EXISTS mytable (
    id SERIAL PRIMARY KEY,
    locationid INT,
    applicant TEXT,
    facilitytype TEXT,
    cnn INT,
    locationdescription TEXT,
    address TEXT,
    blocklot TEXT,
    block TEXT,
    lot TEXT,
    permit TEXT,
    status TEXT,
    fooditems TEXT,
    x FLOAT,
    y FLOAT,
    latitude FLOAT,
    longitude FLOAT,
    schedule TEXT,
    dayshours TEXT,
    noisent TEXT,
    approved TEXT,
    received TEXT,
    priorpermit BOOLEAN,
    expirationdate TEXT,
    location TEXT,
    fire_prevention_districts INT,
    police_districts INT,
    supervisor_districts INT,
    zip_codes INT,
    neighborhoods_old INT
);


COPY mytable(
    locationid,
    applicant,
    facilitytype,
    cnn,
    locationdescription,
    address,
    blocklot,
    block,
    lot,
    permit,
    status,
    fooditems,
    x,
    y,
    latitude,
    longitude,
    schedule,
    dayshours,
    noisent,
    approved,
    received,
    priorpermit,
    expirationdate,
    location,
    fire_prevention_districts,
    police_districts,
    supervisor_districts,
    zip_codes,
    neighborhoods_old
) FROM '/tmp/Mobile_Food_Facility_Permit.csv' DELIMITER ',' CSV HEADER;
